
services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P!@#$55w0rD
      MYSQL_DATABASE: dbmtechwatt   
      MYSQL_USER: wpuser345
      MYSQL_PASSWORD: P!@#$55w0rD
    volumes:
      - db_data:/var/lib/mysql
      - ./dbmtechwatt.sql:/docker-entrypoint-initdb.d/dbmtechwatt.sql:ro
    ports:
      - "3307:3306"

  wordpress:
    image: wordpress:php8.2-apache
    container_name: wp_app
    depends_on:
      - db
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser345
      WORDPRESS_DB_PASSWORD: P!@#$55w0rD
      WORDPRESS_DB_NAME: dbmtechwatt
    command: >
      bash -c "apache2-foreground -e info -C 'ServerName localhost'"
    volumes:
      - .:/var/www/html

volumes:
  db_data:
